Refactor logs endpoint so it uses pagination to send at most 100 logs when receiving a Get request
rancher/opni-insights-service pull request #11
Opened 2021-11-18 18:33 UTC by AmartC

This pull request refactors the logs endpoint by implementing pagination so anytime a Get request is sent to the endpoint, it will return at most 100 logs and also return the scroll_id which can be used to fetch the next page of 100 log messages.

2021-11-20 03:12 UTC, tybalex requested changes

2021-11-20 03:12 UTC, tybalex commented on opni-insights-service/app/main.py
> +    if scroll_id:
I think codes in if/else block are almost the same (except the first line `current_page = xxx`). let's merge them.

2021-11-23 02:07 UTC, sanjay920 approved these changes

2021-11-23 03:18 UTC, tybalex approved these changes

2021-11-23 14:56 UTC, merged